"""Decision and reason codes.

A short entry is intentionally absent. Long equity is the only entry.
Decisions are ENTER_LONG and NO_TRADE. Margin is rejected when config loads.
"""

from __future__ import annotations

from enum import Enum


class DecisionKind(str, Enum):
    ENTER_LONG = "ENTER_LONG"
    NO_TRADE = "NO_TRADE"


class ReasonCode(str, Enum):
    WARN_EXDIV = "WARN_EXDIV"
    WARN_EARNINGS_DISAGREE = "WARN_EARNINGS_DISAGREE"
    WARN_BAR_RECONSTRUCTED = "WARN_BAR_RECONSTRUCTED"
    NOTE_ETF_NO_EARNINGS = "NOTE_ETF_NO_EARNINGS"
    NO_MARKET_DATA = "NO_MARKET_DATA"
    DATA_STALE = "DATA_STALE"
    CORP_ACTION_SUSPECT = "CORP_ACTION_SUSPECT"
    ILLIQUID = "ILLIQUID"
    EXDIV_BLOCK = "EXDIV_BLOCK"
    EARNINGS_UNKNOWN = "EARNINGS_UNKNOWN"
    EQUITY_UNSET = "EQUITY_UNSET"
    HEAT_LIMIT = "HEAT_LIMIT"
    MAX_POSITIONS = "MAX_POSITIONS"
    NO_SETUP = "NO_SETUP"
    ALREADY_OPEN = "ALREADY_OPEN"
    INVALID_STOP = "INVALID_STOP"
    SIZE_BELOW_ONE_SHARE = "SIZE_BELOW_ONE_SHARE"
    NO_NEXT_OPEN = "NO_NEXT_OPEN"
    SETUP_SUPPRESSED = "SETUP_SUPPRESSED"
    EARNINGS_BLACKOUT = "EARNINGS_BLACKOUT"
