"""Decision and reason codes.

ENTER_SHORT is intentionally absent. Long equity is the only entry.
Shariah codes are reserved for a future screener. v0 analyze does not emit them.
"""

from __future__ import annotations

from enum import Enum


class DecisionKind(str, Enum):
    ENTER_LONG = "ENTER_LONG"
    NO_TRADE = "NO_TRADE"
    BLOCK = "BLOCK"


class ReasonCode(str, Enum):
    BLOCK_SHORT = "BLOCK_SHORT"
    BLOCK_MARGIN = "BLOCK_MARGIN"
    BLOCK_DERIVATIVE = "BLOCK_DERIVATIVE"
    BLOCK_SHARIAH_SCREEN = "BLOCK_SHARIAH_SCREEN"
    BLOCK_SHARIAH_SECTOR = "BLOCK_SHARIAH_SECTOR"
    BLOCK_SHARIAH_DATA = "BLOCK_SHARIAH_DATA"
    BLOCK_SHARIAH_QUESTIONABLE = "BLOCK_SHARIAH_QUESTIONABLE"
    BLOCK_SHARIAH_OVERRIDE_DENIED = "BLOCK_SHARIAH_OVERRIDE_DENIED"
    WARN_PURIFICATION = "WARN_PURIFICATION"
    WARN_SHARIAH_STALE = "WARN_SHARIAH_STALE"
    WARN_DIY_SCREEN = "WARN_DIY_SCREEN"
    WARN_SHARIAH_WEAPONS_POLICY = "WARN_SHARIAH_WEAPONS_POLICY"
    WARN_SHARIAH_DISAGREEMENT = "WARN_SHARIAH_DISAGREEMENT"
    WARN_SPY_R2 = "WARN_SPY_R2"
    WARN_EXDIV = "WARN_EXDIV"
    WARN_RESEARCH_UNAVAILABLE = "WARN_RESEARCH_UNAVAILABLE"
    WARN_RESEARCH_ERROR = "WARN_RESEARCH_ERROR"
    WARN_NEWS = "WARN_NEWS"
    WARN_BAR_RECONSTRUCTED = "WARN_BAR_RECONSTRUCTED"
    PIPELINE_NOT_IMPLEMENTED = "PIPELINE_NOT_IMPLEMENTED"
    NO_MARKET_DATA = "NO_MARKET_DATA"
    DATA_STALE = "DATA_STALE"
    CORP_ACTION_SUSPECT = "CORP_ACTION_SUSPECT"
    ILLIQUID = "ILLIQUID"
    EXDIV_BLOCK = "EXDIV_BLOCK"
    EARNINGS_UNKNOWN = "EARNINGS_UNKNOWN"
    EQUITY_UNSET = "EQUITY_UNSET"
    HEAT_LIMIT = "HEAT_LIMIT"
    MAX_POSITIONS = "MAX_POSITIONS"
    ADR_TOO_QUIET = "ADR_TOO_QUIET"
    NO_SETUP = "NO_SETUP"
    INVALID_STOP = "INVALID_STOP"
    SIZE_BELOW_ONE_SHARE = "SIZE_BELOW_ONE_SHARE"
    NO_NEXT_OPEN = "NO_NEXT_OPEN"
    SETUP_SUPPRESSED = "SETUP_SUPPRESSED"
    EARNINGS_BLACKOUT = "EARNINGS_BLACKOUT"


SHARIAH_REASON_CODES = frozenset(
    {
        ReasonCode.BLOCK_SHARIAH_SCREEN,
        ReasonCode.BLOCK_SHARIAH_SECTOR,
        ReasonCode.BLOCK_SHARIAH_DATA,
        ReasonCode.BLOCK_SHARIAH_QUESTIONABLE,
        ReasonCode.BLOCK_SHARIAH_OVERRIDE_DENIED,
        ReasonCode.WARN_PURIFICATION,
        ReasonCode.WARN_SHARIAH_STALE,
        ReasonCode.WARN_DIY_SCREEN,
        ReasonCode.WARN_SHARIAH_WEAPONS_POLICY,
        ReasonCode.WARN_SHARIAH_DISAGREEMENT,
    }
)
